# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8ebf02d895528cd10f5bed84afa4763bdce099d7d065d8cc8ffccd87eb772990d0d25f83ae5b80e0e9f7bc04cc00fe071c928f4cb056005cc4fb981dfcb4f27
  postmark_api_token: "e0ab21a2-3d3b-432b-8a77-132f25b58aa"
test:
  secret_key_base: 280faae7d7ae0fc50e8a7182d242ad2566c72588d2275dbbd37b99f1da4e8fe4c7b77f1bd66691ad2bb919862dc211d9ff127129a7936c65b152d12f1aa355f8
  postmark_api_token: "e0ab21a2-3d3b-432b-8a77-132f25b58aa"
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postmark_api_token: "e0ab21a2-3d3b-432b-8a77-132f25b58aa"
