require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe EmailsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Email. As you add validations to Email, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    # Valid attributes are generated using FactoryGirl
    FactoryGirl.attributes_for(:email)
  }

  let(:invalid_attributes) {
    {email_address: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do

    # Check to see if app_id param is given, it returns a success response
    it 'returns a success response if app_id param is given' do
      email = Email.create! valid_attributes
      get :index, params: {app_id: email.app_id}, session: valid_session
      expect(response).to be_success
    end

    # Check to see if app_id and email_list_id param is given, it returns a success response
    it 'returns a success response if app_id and email_list_id param is given' do
      email = Email.create! valid_attributes
      get :index, params: {app_id: email.app_id, email_list_id: email.email_list_id}, session: valid_session
      expect(response).to be_success
    end

    # Check to see if only email_list_id param is given, it returns a success response
    it 'returns a success response if email_list_id param is given' do
      email = Email.create! valid_attributes
      get :index, params: {email_list_id: email.email_list_id}, session: valid_session
      expect(response).to be_success
    end

    it "returns a success response" do
      get :index, params: {}, session: valid_session
      expect(response).to be_success
    end


  end

  describe "GET #show" do
    it "returns a success response" do
      email = Email.create! valid_attributes
      get :show, params: {id: email.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Email" do
        expect {
          post :create, params: {email: valid_attributes}, session: valid_session
        }.to change(Email, :count).by(1)
      end

      it "renders a JSON response with the new email" do

        post :create, params: {email: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.location).to eq(email_url(Email.last))
      end

      # Check to see if it renders and error response if email is not saved
      it 'renders an error JSON response if new email not saved' do
        # Set app.save to false
        allow_any_instance_of(Email).to receive(:save).and_return(false)
        post :create, params: {email: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
      end


    end

  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: "NewName"}
      }

      it "updates the requested email" do
        email = Email.create! valid_attributes
        put :update, params: {id: email.to_param, email: new_attributes}, session: valid_session
        email.reload
        email.name == "NewName"
      end

      it "renders a JSON response with the email" do
        email = Email.create! valid_attributes
        put :update, params: {id: email.to_param, email: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:ok)
      end

      # Check to see if it renders and error response if email not updated
      it 'renders an error JSON response if email is not updated' do
        email = Email.create! valid_attributes
        # Set app.save to false
        allow_any_instance_of(Email).to receive(:update).with(any_args).and_return(false)
        post :update, params: {id: email.to_param, email: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end

  end

  describe "DELETE #destroy" do
    it "destroys the requested email" do
      email = Email.create! valid_attributes
      expect {
        delete :destroy, params: {id: email.to_param}, session: valid_session
      }.to change(Email, :count).by(-1)
    end
  end

end
