require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TestmodelsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Testmodel. As you add validations to Testmodel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TestmodelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all testmodels as @testmodels" do
      testmodel = Testmodel.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:testmodels)).to eq([testmodel])
    end
  end

  describe "GET show" do
    it "assigns the requested testmodel as @testmodel" do
      testmodel = Testmodel.create! valid_attributes
      get :show, {:id => testmodel.to_param}, valid_session
      expect(assigns(:testmodel)).to eq(testmodel)
    end
  end

  describe "GET new" do
    it "assigns a new testmodel as @testmodel" do
      get :new, {}, valid_session
      expect(assigns(:testmodel)).to be_a_new(Testmodel)
    end
  end

  describe "GET edit" do
    it "assigns the requested testmodel as @testmodel" do
      testmodel = Testmodel.create! valid_attributes
      get :edit, {:id => testmodel.to_param}, valid_session
      expect(assigns(:testmodel)).to eq(testmodel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Testmodel" do
        expect {
          post :create, {:testmodel => valid_attributes}, valid_session
        }.to change(Testmodel, :count).by(1)
      end

      it "assigns a newly created testmodel as @testmodel" do
        post :create, {:testmodel => valid_attributes}, valid_session
        expect(assigns(:testmodel)).to be_a(Testmodel)
        expect(assigns(:testmodel)).to be_persisted
      end

      it "redirects to the created testmodel" do
        post :create, {:testmodel => valid_attributes}, valid_session
        expect(response).to redirect_to(Testmodel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved testmodel as @testmodel" do
        post :create, {:testmodel => invalid_attributes}, valid_session
        expect(assigns(:testmodel)).to be_a_new(Testmodel)
      end

      it "re-renders the 'new' template" do
        post :create, {:testmodel => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested testmodel" do
        testmodel = Testmodel.create! valid_attributes
        put :update, {:id => testmodel.to_param, :testmodel => new_attributes}, valid_session
        testmodel.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested testmodel as @testmodel" do
        testmodel = Testmodel.create! valid_attributes
        put :update, {:id => testmodel.to_param, :testmodel => valid_attributes}, valid_session
        expect(assigns(:testmodel)).to eq(testmodel)
      end

      it "redirects to the testmodel" do
        testmodel = Testmodel.create! valid_attributes
        put :update, {:id => testmodel.to_param, :testmodel => valid_attributes}, valid_session
        expect(response).to redirect_to(testmodel)
      end
    end

    describe "with invalid params" do
      it "assigns the testmodel as @testmodel" do
        testmodel = Testmodel.create! valid_attributes
        put :update, {:id => testmodel.to_param, :testmodel => invalid_attributes}, valid_session
        expect(assigns(:testmodel)).to eq(testmodel)
      end

      it "re-renders the 'edit' template" do
        testmodel = Testmodel.create! valid_attributes
        put :update, {:id => testmodel.to_param, :testmodel => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested testmodel" do
      testmodel = Testmodel.create! valid_attributes
      expect {
        delete :destroy, {:id => testmodel.to_param}, valid_session
      }.to change(Testmodel, :count).by(-1)
    end

    it "redirects to the testmodels list" do
      testmodel = Testmodel.create! valid_attributes
      delete :destroy, {:id => testmodel.to_param}, valid_session
      expect(response).to redirect_to(testmodels_url)
    end
  end

end
